name: AI_CULL_SHARE_EVENTIZE
version: ''
services:
  web:
    build: .
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - redis_dev
      - database_dev
      - rabbit_MQ_dev

  database_dev:
    image: postgres 16.4
    environment:
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      - POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
  
  redis_dev:
    image: redis 7.4
    ports:
      - 
  
  rabbit_MQ_dev:
    image: rabbitmq 3.13.7
    ports:
      - 15672:15672
  
  celery_dev: