name: ai_cull_share_eventize

services:
  backend:
    build: .
    container_name: backend
    env_file:
      - .env
    environment:
      - TRANSFORMERS_CACHE=/app/.cache
    ports:
      - 8000:8000
    volumes:
      - ./static:/app/static
      - huggingface_cache:/app/.cache/huggingface

  celery_dev:
    build: .
    container_name: celery_worker
    command: celery -A src.main.main.celery worker --loglevel=info --pool=solo
    env_file:
      - .env
    environment:
      - TRANSFORMERS_CACHE=/app/.cache
      - C_FORCE_ROOT=true
    volumes:
      - ./static:/app/static
      - huggingface_cache:/app/.cache/huggingface
    depends_on:
      - backend

volumes:
  huggingface_cache: