name: AI_CULL_SHARE_EVENTIZE


services:
  backend:
    build: .
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - redis_dev
      - database_dev
      - rabbit_MQ_dev
      - celery_dev

  database_dev:
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  celery_dev:
    container_name: celery_worker
    build: .
    command: celery -A src.main.main.celery worker --loglevel=info --pool=solo
    depends_on:
      - redis_dev

  redis_dev:
    image: redis:7.4.1
    ports:
      - 6379:6379

  rabbit_MQ_dev:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
