"""added culling_in_progress feild in folder_in_s3 table to check wheather the culling is complete or not

Revision ID: 0e9a12e82498
Revises: 369a43c3f15a
Create Date: 2024-11-15 20:38:54.594072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e9a12e82498'
down_revision: Union[str, None] = '369a43c3f15a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_s3_folders', sa.Column('culling_in_progress', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_s3_folders', 'culling_in_progress')
    # ### end Alembic commands ###
