"""do some changes in CulledImagesMetadata and SmartShareImagesMetadata

Revision ID: 113f6ad504a6
Revises: 72dab99f5ade
Create Date: 2025-02-18 19:17:31.034829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '113f6ad504a6'
down_revision: Union[str, None] = '72dab99f5ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('culling_images_metadata', sa.Column('image_download_path', sa.String(), nullable=False))
    op.add_column('culling_images_metadata', sa.Column('image_download_validity', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('culling_images_metadata', 'images_download_validity')
    op.drop_column('culling_images_metadata', 'images_download_path')
    op.add_column('smart_share_images_metadata', sa.Column('image_download_path', sa.String(), nullable=False))
    op.add_column('smart_share_images_metadata', sa.Column('image_download_validity', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('smart_share_images_metadata', 'images_download_validity')
    op.drop_column('smart_share_images_metadata', 'images_download_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smart_share_images_metadata', sa.Column('images_download_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('smart_share_images_metadata', sa.Column('images_download_validity', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('smart_share_images_metadata', 'image_download_validity')
    op.drop_column('smart_share_images_metadata', 'image_download_path')
    op.add_column('culling_images_metadata', sa.Column('images_download_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('culling_images_metadata', sa.Column('images_download_validity', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('culling_images_metadata', 'image_download_validity')
    op.drop_column('culling_images_metadata', 'image_download_path')
    # ### end Alembic commands ###
