"""Add detection_status in ImagesMetaData Column

Revision ID: 23a72ab04b11
Revises: 1f98f61eee7e
Create Date: 2024-11-14 10:05:45.946723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23a72ab04b11'
down_revision: Union[str, None] = '1f98f61eee7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imagesmetadata', sa.Column('detection_status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imagesmetadata', 'detection_status')
    # ### end Alembic commands ###
