"""added association table between smart share folder and secondary user

Revision ID: 26d859caac1b
Revises: e29f0b3c1fee
Create Date: 2025-01-28 10:06:20.889833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26d859caac1b'
down_revision: Union[str, None] = 'e29f0b3c1fee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smart_share_folders_secondary_user_association',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('secondary_user_id', sa.UUID(), nullable=False),
    sa.Column('smart_share_folder_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['secondary_user_id'], ['secondary_user.user_id'], ),
    sa.ForeignKeyConstraint(['smart_share_folder_id'], ['smart_share_folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('secondary_user', 'event_id')
    op.drop_column('secondary_user', 'access_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secondary_user', sa.Column('access_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('secondary_user', sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_table('smart_share_folders_secondary_user_association')
    # ### end Alembic commands ###
