"""fixed association between secondary user and smart share folders

Revision ID: 274db7cafe26
Revises: 20560bfce18b
Create Date: 2025-01-29 10:12:52.277580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '274db7cafe26'
down_revision: Union[str, None] = '20560bfce18b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
