"""added temporary_presigned_image_urls for storing temporary presigned url

Revision ID: 367e006058da
Revises: 448c2777f75a
Create Date: 2024-10-12 15:40:28.849969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '367e006058da'
down_revision: Union[str, None] = '448c2777f75a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporary_presigned_image_urls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('validity', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('folder_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['user_s3_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temporary_presigned_image_urls_id'), 'temporary_presigned_image_urls', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temporary_presigned_image_urls_id'), table_name='temporary_presigned_image_urls')
    op.drop_table('temporary_presigned_image_urls')
    # ### end Alembic commands ###
