"""remove tmporary url table and add a feild of temporary temporary_images_url

Revision ID: 39c68a32cfd4
Revises: 23a72ab04b11
Create Date: 2024-11-14 14:10:23.497158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39c68a32cfd4'
down_revision: Union[str, None] = '23a72ab04b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_temporary_presigned_image_urls_id', table_name='temporary_presigned_image_urls')
    op.drop_table('temporary_presigned_image_urls')
    op.add_column('user_s3_folders', sa.Column('temporary_images_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_s3_folders', 'temporary_images_urls')
    op.create_table('temporary_presigned_image_urls',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('validity', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('folder_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['user_s3_folders.id'], name='temporary_presigned_image_urls_folder_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='temporary_presigned_image_urls_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='temporary_presigned_image_urls_pkey')
    )
    op.create_index('ix_temporary_presigned_image_urls_id', 'temporary_presigned_image_urls', ['id'], unique=False)
    # ### end Alembic commands ###
