"""added cover image in SmartShareFolderModel

Revision ID: 39e6233322cb
Revises: a431622b68f1
Create Date: 2024-12-11 11:24:05.822816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e6233322cb'
down_revision: Union[str, None] = 'a431622b68f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smart_share_folders', sa.Column('cover_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smart_share_folders', 'cover_image')
    # ### end Alembic commands ###
