"""added culling_done table marke it true when culling done

Revision ID: 5e4fef5969d4
Revises: 39c68a32cfd4
Create Date: 2024-11-15 09:34:46.264947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4fef5969d4'
down_revision: Union[str, None] = '39c68a32cfd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('culling_done', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'culling_done')
    # ### end Alembic commands ###
