"""linked association table with user

Revision ID: 5ea00f38a7d2
Revises: 274db7cafe26
Create Date: 2025-01-29 19:34:32.783359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea00f38a7d2'
down_revision: Union[str, None] = '274db7cafe26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secondary_user')
    op.add_column('smart_share_folders_secondary_user_association', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_constraint('smart_share_folders_secondary_user_assoc_secondary_user_id_fkey', 'smart_share_folders_secondary_user_association', type_='foreignkey')
    op.create_foreign_key(None, 'smart_share_folders_secondary_user_association', 'users', ['user_id'], ['id'])
    op.drop_column('smart_share_folders_secondary_user_association', 'secondary_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smart_share_folders_secondary_user_association', sa.Column('secondary_user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'smart_share_folders_secondary_user_association', type_='foreignkey')
    op.create_foreign_key('smart_share_folders_secondary_user_assoc_secondary_user_id_fkey', 'smart_share_folders_secondary_user_association', 'secondary_user', ['secondary_user_id'], ['user_id'])
    op.drop_column('smart_share_folders_secondary_user_association', 'user_id')
    op.create_table('secondary_user',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name='secondary_user_pkey')
    )
    # ### end Alembic commands ###
