"""added status feild in SmartShare Folder

Revision ID: 72dab99f5ade
Revises: a99515ece463
Create Date: 2025-02-16 15:09:14.962633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72dab99f5ade'
down_revision: Union[str, None] = 'a99515ece463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define the Enum type
publish_status_enum = sa.Enum('Published', 'Not Published', 'Pending', name='publishstatus')


def upgrade() -> None:
    # Create the enum type in PostgreSQL
    publish_status_enum.create(op.get_bind(), checkfirst=True)

    # Add the new column using the created enum
    op.add_column('smart_share_folders', sa.Column('status', publish_status_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smart_share_folders', 'status')
    # ### end Alembic commands ###
    
    # Drop the enum type
    publish_status_enum.drop(op.get_bind(), checkfirst=True)
