"""updated user schema changed phone to phone_numbers

Revision ID: 7600b4fba3b4
Revises: ffbdd59068b3
Create Date: 2024-12-04 11:50:51.905513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7600b4fba3b4'
down_revision: Union[str, None] = 'ffbdd59068b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_numbers', sa.JSON(), nullable=True))
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('users', 'phone_numbers')
    # ### end Alembic commands ###
