"""added contact us model

Revision ID: 8f867158758f
Revises: f49ccdf4f0fd
Create Date: 2025-02-01 16:16:02.811604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f867158758f'
down_revision: Union[str, None] = 'f49ccdf4f0fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_us',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_numbers', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('contact_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_us_email'), 'contact_us', ['email'], unique=True)
    op.create_index(op.f('ix_contact_us_id'), 'contact_us', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_us_id'), table_name='contact_us')
    op.drop_index(op.f('ix_contact_us_email'), table_name='contact_us')
    op.drop_table('contact_us')
    # ### end Alembic commands ###
