"""update temp images url table

Revision ID: 9add804f9e09
Revises: eddbee75cbfe
Create Date: 2025-01-14 21:36:13.941246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9add804f9e09'
down_revision: Union[str, None] = 'eddbee75cbfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temporary_culling_image_urls_metadata', sa.Column('name', sa.String(), nullable=False))
    op.add_column('temporary_culling_image_urls_metadata', sa.Column('file_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temporary_culling_image_urls_metadata', 'file_type')
    op.drop_column('temporary_culling_image_urls_metadata', 'name')
    # ### end Alembic commands ###
