"""changed model of event_arrangment_form

Revision ID: 9e9fc3bae825
Revises: c87753c6eab7
Create Date: 2024-12-06 14:21:44.226889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e9fc3bae825'
down_revision: Union[str, None] = 'c87753c6eab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_arrangment_form', sa.Column('fullName', sa.String(length=100), nullable=False))
    op.add_column('event_arrangment_form', sa.Column('eventType', sa.String(length=100), nullable=False))
    op.add_column('event_arrangment_form', sa.Column('eventDescription', sa.Text(), nullable=True))
    op.add_column('event_arrangment_form', sa.Column('eventDate', sa.DateTime(), nullable=False))
    op.add_column('event_arrangment_form', sa.Column('numberOfGuests', sa.Integer(), nullable=False))
    op.add_column('event_arrangment_form', sa.Column('selectCountry', sa.String(length=100), nullable=False))
    op.add_column('event_arrangment_form', sa.Column('alternativeCity', sa.String(length=100), nullable=True))
    op.add_column('event_arrangment_form', sa.Column('specialRequirements', sa.Text(), nullable=True))
    op.add_column('event_arrangment_form', sa.Column('submittedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('event_arrangment_form', sa.Column('userId', sa.String(), nullable=False))
    op.drop_constraint('event_arrangment_form_user_id_fkey', 'event_arrangment_form', type_='foreignkey')
    op.create_foreign_key(None, 'event_arrangment_form', 'users', ['userId'], ['id'])
    op.drop_column('event_arrangment_form', 'full_name')
    op.drop_column('event_arrangment_form', 'number_of_guests')
    op.drop_column('event_arrangment_form', 'event_date')
    op.drop_column('event_arrangment_form', 'user_id')
    op.drop_column('event_arrangment_form', 'event_description')
    op.drop_column('event_arrangment_form', 'submitted_at')
    op.drop_column('event_arrangment_form', 'special_requirements')
    op.drop_column('event_arrangment_form', 'alternative_city')
    op.drop_column('event_arrangment_form', 'event_type')
    op.drop_column('event_arrangment_form', 'select_country')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_arrangment_form', sa.Column('select_country', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('event_arrangment_form', sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('event_arrangment_form', sa.Column('alternative_city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('event_arrangment_form', sa.Column('special_requirements', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('event_arrangment_form', sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('event_arrangment_form', sa.Column('event_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('event_arrangment_form', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('event_arrangment_form', sa.Column('event_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('event_arrangment_form', sa.Column('number_of_guests', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('event_arrangment_form', sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'event_arrangment_form', type_='foreignkey')
    op.create_foreign_key('event_arrangment_form_user_id_fkey', 'event_arrangment_form', 'users', ['user_id'], ['id'])
    op.drop_column('event_arrangment_form', 'userId')
    op.drop_column('event_arrangment_form', 'submittedAt')
    op.drop_column('event_arrangment_form', 'specialRequirements')
    op.drop_column('event_arrangment_form', 'alternativeCity')
    op.drop_column('event_arrangment_form', 'selectCountry')
    op.drop_column('event_arrangment_form', 'numberOfGuests')
    op.drop_column('event_arrangment_form', 'eventDate')
    op.drop_column('event_arrangment_form', 'eventDescription')
    op.drop_column('event_arrangment_form', 'eventType')
    op.drop_column('event_arrangment_form', 'fullName')
    # ### end Alembic commands ###
