"""converted TemporaryImageURL validity to datetime

Revision ID: a431622b68f1
Revises: eb68a413eee9
Create Date: 2024-12-07 18:54:04.530272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a431622b68f1'
down_revision: Union[str, None] = 'eb68a413eee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporary_culling_image_urls_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('validity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('culling_folder_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['culling_folder_id'], ['culling_folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temporary_culling_image_urls_metadata')
    # ### end Alembic commands ###
