"""fixed the problem when any smart share event delete it will give me FK constrainr error

Revision ID: a99515ece463
Revises: cc18a5b3a90a
Create Date: 2025-02-09 19:33:14.362669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a99515ece463'
down_revision: Union[str, None] = 'cc18a5b3a90a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('smart_share_folders_users_associatio_smart_share_folder_id_fkey', 'smart_share_folders_users_association', type_='foreignkey')
    op.drop_constraint('smart_share_folders_users_association_user_id_fkey', 'smart_share_folders_users_association', type_='foreignkey')
    op.create_foreign_key(None, 'smart_share_folders_users_association', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'smart_share_folders_users_association', 'smart_share_folders', ['smart_share_folder_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'smart_share_folders_users_association', type_='foreignkey')
    op.drop_constraint(None, 'smart_share_folders_users_association', type_='foreignkey')
    op.create_foreign_key('smart_share_folders_users_association_user_id_fkey', 'smart_share_folders_users_association', 'users', ['user_id'], ['id'])
    op.create_foreign_key('smart_share_folders_users_associatio_smart_share_folder_id_fkey', 'smart_share_folders_users_association', 'smart_share_folders', ['smart_share_folder_id'], ['id'])
    # ### end Alembic commands ###
