"""fixed contact us model

Revision ID: b411f9d4d08f
Revises: 8f867158758f
Create Date: 2025-02-01 16:27:29.979037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b411f9d4d08f'
down_revision: Union[str, None] = '8f867158758f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_us', sa.Column('phone', sa.String(), nullable=True))
    op.drop_column('contact_us', 'phone_numbers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_us', sa.Column('phone_numbers', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('contact_us', 'phone')
    # ### end Alembic commands ###
