"""added EventArrangmentBook table

Revision ID: c87753c6eab7
Revises: 7a5ea95e98e2
Create Date: 2024-12-05 15:47:16.532014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87753c6eab7'
down_revision: Union[str, None] = '7a5ea95e98e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_arrangment_form',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('number_of_guests', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('select_country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('alternative_city', sa.String(length=100), nullable=True),
    sa.Column('portfolio', sa.String(length=100), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_arrangment_form')
    # ### end Alembic commands ###
