"""added accessed_at field in SmartShareFoldersSecondaryUsersAssociation table

Revision ID: cc18a5b3a90a
Revises: d911bcb41a52
Create Date: 2025-02-09 18:59:15.250797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc18a5b3a90a'
down_revision: Union[str, None] = 'd911bcb41a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smart_share_folders_users_association', sa.Column('accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smart_share_folders_users_association', 'accessed_at')
    # ### end Alembic commands ###
