"""fixed contact us model by removing unique=True from email

Revision ID: d911bcb41a52
Revises: b411f9d4d08f
Create Date: 2025-02-01 16:37:02.140261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd911bcb41a52'
down_revision: Union[str, None] = 'b411f9d4d08f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contact_us_email', table_name='contact_us')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_contact_us_email', 'contact_us', ['email'], unique=True)
    # ### end Alembic commands ###
