"""Fix secondary user model

Revision ID: e29f0b3c1fee
Revises: d2db89ddfd1b
Create Date: 2025-01-27 18:53:24.924901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e29f0b3c1fee'
down_revision: Union[str, None] = 'd2db89ddfd1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secondary_user', sa.Column('last_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('secondary_user', 'last_name')
    # ### end Alembic commands ###
