"""changed my all models

Revision ID: eb68a413eee9
Revises: de6d566b4c68
Create Date: 2024-12-07 16:58:45.021085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb68a413eee9'
down_revision: Union[str, None] = 'de6d566b4c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('culling_folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('path_in_s3', sa.String(), nullable=False),
    sa.Column('total_size', sa.Integer(), nullable=False),
    sa.Column('culling_done', sa.Boolean(), nullable=False),
    sa.Column('culling_in_progress', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smart_share_folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('path_in_s3', sa.String(), nullable=False),
    sa.Column('total_size', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('culling_images_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('upload_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('images_download_path', sa.String(), nullable=False),
    sa.Column('images_download_validity', sa.DateTime(timezone=True), nullable=False),
    sa.Column('culling_folder_id', sa.UUID(), nullable=False),
    sa.Column('detection_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['culling_folder_id'], ['culling_folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smart_share_images_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('upload_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('images_download_path', sa.String(), nullable=False),
    sa.Column('images_download_validity', sa.DateTime(timezone=True), nullable=False),
    sa.Column('smart_share_folder_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['smart_share_folder_id'], ['smart_share_folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temporary_culling_image_urls_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('validity', sa.String(), nullable=True),
    sa.Column('culling_folder_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['culling_folder_id'], ['culling_folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('imagesmetadata')
    op.drop_table('user_s3_folders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_s3_folders',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('location_in_s3', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('module', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('temporary_images_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('culling_done', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('culling_in_progress', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_s3_folders_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_s3_folders_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('imagesmetadata',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('upload_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('download_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('link_validity', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('folder_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('detection_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['user_s3_folders.id'], name='imagesmetadata_folder_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='imagesmetadata_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='imagesmetadata_pkey')
    )
    op.drop_table('temporary_culling_image_urls_metadata')
    op.drop_table('smart_share_images_metadata')
    op.drop_table('culling_images_metadata')
    op.drop_table('smart_share_folders')
    op.drop_table('culling_folders')
    # ### end Alembic commands ###
