"""changed the model of smart share folder added description column

Revision ID: eddbee75cbfe
Revises: 39e6233322cb
Create Date: 2024-12-13 10:00:14.309874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eddbee75cbfe'
down_revision: Union[str, None] = '39e6233322cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smart_share_folders', sa.Column('description', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smart_share_folders', 'description')
    # ### end Alembic commands ###
