"""created SmartShareFoldersSecondaryUsersAssociation and linked it with smart share folder and users

Revision ID: f49ccdf4f0fd
Revises: 5ea00f38a7d2
Create Date: 2025-01-29 20:14:56.667278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49ccdf4f0fd'
down_revision: Union[str, None] = '5ea00f38a7d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smart_share_folders_users_association',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('smart_share_folder_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['smart_share_folder_id'], ['smart_share_folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smart_share_folders_users_association')
    # ### end Alembic commands ###
